---
# Source: kube-arangodb-test/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
    name: arangodb-test
    namespace: default
    labels:
        app.kubernetes.io/name: kube-arangodb-test
        helm.sh/chart: kube-arangodb-test-0.4.2
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/instance: arangodb-test
        release: arangodb-test
---
# Source: kube-arangodb-test/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: kube-arangodb-test-arangodb-test
    namespace: default
    labels:
        app.kubernetes.io/name: kube-arangodb-test
        helm.sh/chart: kube-arangodb-test-0.4.2
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/instance: arangodb-test
        release: arangodb-test
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
subjects:
    - kind: ServiceAccount
      name: arangodb-test
      namespace: default
