apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangopermissiontokens.permission.arangodb.com
spec:
  group: permission.arangodb.com
  names:
    kind: ArangoPermissionToken
    listKind: ArangoPermissionTokenList
    plural: arangopermissiontokens
    singular: arangopermissiontoken
    shortNames:
      - arangotoken
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: '.status.conditions[?(@.type=="Ready")].status'
          description: Defines if Token is valid
          name: Ready
          type: string
      subresources:
        status: {}
