# File: chart/kube-arangodb/crds/apps-job.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangojobs.apps.arangodb.com
spec:
  group: apps.arangodb.com
  names:
    kind: ArangoJob
    listKind: ArangoJobList
    plural: arangojobs
    singular: arangojob
    shortNames:
      - arangojob
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.arangoDeploymentName
          description: Deployment name
          name: ArangoDeploymentName
          type: string
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/backups-backup.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangobackups.backup.arangodb.com
spec:
  group: backup.arangodb.com
  names:
    kind: ArangoBackup
    listKind: ArangoBackupList
    plural: arangobackups
    shortNames:
      - arangobackup
    singular: arangobackup
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.policyName
          description: Policy name
          name: Policy
          type: string
        - jsonPath: .spec.deployment.name
          description: Deployment name
          name: Deployment
          type: string
        - jsonPath: .status.backup.version
          description: Backup Version
          name: Version
          type: string
        - jsonPath: .status.backup.createdAt
          description: Backup Creation Timestamp
          name: Created
          type: string
        - jsonPath: .status.backup.sizeInBytes
          description: Backup Size in Bytes
          name: Size
          type: integer
          format: byte
        - jsonPath: .status.backup.numberOfDBServers
          description: Backup Number of the DB Servers
          name: DBServers
          type: integer
        - jsonPath: .status.state
          description: The actual state of the ArangoBackup
          name: State
          type: string
        - jsonPath: .status.message
          priority: 1
          description: Message of the ArangoBackup object
          name: Message
          type: string
      subresources:
        status: {}
    - name: v1alpha
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      additionalPrinterColumns:
        - jsonPath: .spec.policyName
          description: Policy name
          name: Policy
          type: string
        - jsonPath: .spec.deployment.name
          description: Deployment name
          name: Deployment
          type: string
        - jsonPath: .status.backup.version
          description: Backup Version
          name: Version
          type: string
        - jsonPath: .status.backup.createdAt
          description: Backup Creation Timestamp
          name: Created
          type: string
        - jsonPath: .status.backup.sizeInBytes
          description: Backup Size in Bytes
          name: Size
          type: integer
          format: byte
        - jsonPath: .status.backup.numberOfDBServers
          description: Backup Number of the DB Servers
          name: DBServers
          type: integer
        - jsonPath: .status.state
          description: The actual state of the ArangoBackup
          name: State
          type: string
        - jsonPath: .status.message
          priority: 1
          description: Message of the ArangoBackup object
          name: Message
          type: string
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/backups-backuppolicy.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangobackuppolicies.backup.arangodb.com
spec:
  group: backup.arangodb.com
  names:
    kind: ArangoBackupPolicy
    listKind: ArangoBackupPolicyList
    plural: arangobackuppolicies
    shortNames:
      - arangobackuppolicy
      - arangobp
    singular: arangobackuppolicy
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.schedule
          description: Schedule
          name: Schedule
          type: string
        - jsonPath: .status.scheduled
          description: Scheduled
          name: Scheduled
          type: string
        - jsonPath: .status.message
          priority: 1
          description: Message of the ArangoBackupPolicy object
          name: Message
          type: string
      subresources:
        status: {}
    - name: v1alpha
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      additionalPrinterColumns:
        - jsonPath: .spec.schedule
          description: Schedule
          name: Schedule
          type: string
        - jsonPath: .status.scheduled
          description: Scheduled
          name: Scheduled
          type: string
        - jsonPath: .status.message
          priority: 1
          description: Message of the ArangoBackupPolicy object
          name: Message
          type: string
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/database-clustersynchronization.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoclustersynchronizations.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoClusterSynchronization
    listKind: ArangoClusterSynchronizationList
    plural: arangoclustersynchronizations
    singular: arangoclustersynchronization
    shortNames:
      - arangoclustersync
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/database-deployment.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangodeployments.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoDeployment
    listKind: ArangoDeploymentList
    plural: arangodeployments
    shortNames:
      - arangodb
      - arango
    singular: arangodeployment
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
    - name: v1alpha
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/database-member.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangomembers.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoMember
    listKind: ArangoMemberList
    plural: arangomembers
    shortNames:
      - arangomembers
    singular: arangomember
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/database-task.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangotasks.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoTask
    listKind: ArangoTaskList
    plural: arangotasks
    singular: arangotask
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
    - name: v1alpha
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/replication-deploymentreplication.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangodeploymentreplications.replication.database.arangodb.com
spec:
  group: replication.database.arangodb.com
  names:
    kind: ArangoDeploymentReplication
    listKind: ArangoDeploymentReplicationList
    plural: arangodeploymentreplications
    shortNames:
      - arangorepl
    singular: arangodeploymentreplication
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
    - name: v1alpha
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
